services:
  api:
    build: .
    container_name: intranet_produccion_api
    restart: unless-stopped
    expose:
      - "8002"
    env_file:
      - .env
    volumes:
      - /home/ec2-user/.aws:/root/.aws:ro
    networks:
      - intranet_gestion_auth_network
    environment:
      DB_HOST: mysql-db-api-auth

networks:
  intranet_gestion_auth_network:
    external: true